#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

typedef vector<int> vi;
typedef vector<pair<int, int>> vpii;

#define eps 1e-14

long long change_base(long long k, string n) {
    long long ans = 0;
    for (int i = 0; i < n.size(); i++) {
        ans = ans * k + (n[i]-'0');
    }
    return ans;
}

void solve(long long K, string A, string B) {
    long long a = change_base(K, A);
    long long b = change_base(K, B);
    cout << a * b << endl;
}

// Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools templates:
// (https://github.com/imishinist/competitive/blob/master/boilerplate/main.cpp)
int main() {
    long long K;
    std::scanf("%lld", &K);
    string A, B;
    cin >> A >> B;
    solve(K, A, B);
    return 0;
}
