#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

typedef vector<int> vi;
typedef vector<pair<int, int>> vpii;
typedef long long ll;

#define eps 1e-14

void solve(long long N, std::vector<long long> V, std::vector<long long> C) {
    ll ans = 0;
    for (int i = 0; i < N; i++) {
        if (V[i] > C[i]) {
            ans += (V[i] - C[i]);
        }
    }
    cout << ans << endl;
}

// Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools templates:
// (https://github.com/imishinist/competitive/blob/master/boilerplate/main.cpp)
int main() {
    long long N;
    std::scanf("%lld", &N);
    std::vector<long long> V(N);
    for (int i = 0; i < N; i++) {
        std::scanf("%lld", &V[i]);
    }
    std::vector<long long> C(N);
    for (int i = 0; i < N; i++) {
        std::scanf("%lld", &C[i]);
    }
    solve(N, std::move(V), std::move(C));
    return 0;
}
