#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

typedef vector<int> vi;
typedef vector<pair<int, int>> vpii;

#define eps 1e-14


void solve(string S) {
    vector<int> N;
    for (int i = 0; i < S.size(); i++) {
        N.push_back(S[i] - '0');
    }
    sort(N.begin(), N.end());

    int ans = 0;
    do {
        for (int i = 1; i < N.size(); i++) {
            int l = 0, r = 0;
            for (int j = 0; j < i; j++) l = l * 10 +N[j];
            for (int j = i; j < N.size(); j++) r = r * 10 +N[j];
            ans = max(ans, l * r);
        }
    } while (next_permutation(N.begin(), N.end()));
    cout << ans << endl;
}

// Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools templates:
// (https://github.com/imishinist/competitive/blob/master/boilerplate/main.cpp)
int main() {
    string s;
    cin >> s;
    solve(s);
    return 0;
}
