#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

typedef vector<int> vi;
typedef vector<pair<int, int>> vpii;

#define eps 1e-14


// Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools templates:
// (https://github.com/imishinist/competitive/blob/master/boilerplate/main.cpp)
int main() {
    long long N;
    cin >> N;
    vector<long long> ans(N+1);
    for (int i = 0; i < N; i++) ans[i] = 0;

    vector<pair<long long, long long>> V;
    for (int i = 0; i < N; i++) {
        long long a, b;
        cin >> a >> b;

        V.push_back(make_pair(a, 1));
        V.push_back(make_pair(a+b, -1));
    }
    sort(V.begin(), V.end());

    long long cnt = 0;
    for (int i = 0; i < V.size()-1; i++) {
        int len = V[i+1].first - V[i].first;
        cnt += V[i].second;
        ans[cnt] += len;
    }
    for (int i = 0; i < N-1; i++) {
        cout << ans[i+1] << " ";

    }
    cout << ans[N] << endl;

    return 0;
}
