#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
#include <atcoder/all>
using namespace std;

typedef vector<int> vi;
typedef vector<pair<int, int>> vpii;

using mint = atcoder::modint998244353;

#define eps 1e-14

const long long MOD = 998244353;

void solve(long long N, long long D) {
    set<int> S;
}

// Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools templates:
// (https://github.com/imishinist/competitive/blob/master/boilerplate/main.cpp)
int main() {
    long long N;
    std::scanf("%lld", &N);
    long long D;
    std::scanf("%lld", &D);
    solve(N, D);
    return 0;
}
