#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

typedef vector<int> vi;
typedef vector<pair<int, int>> vpii;
typedef long long ll;

#define eps 1e-14

class State {
public:
    long long r, g, b, count;
    State(){}
    State(ll r, ll g, ll b, ll count):r(r),g(g), b(b), count(count){}
};

ll solve(long long r, long long g, long long b) {
    long mx = max(r, max(g, b)) + 1;
    long long p1 = mx, p2 = mx, p3 = mx;
    // r
    if (abs(g - b) % 3 == 0) {
        p1 = max(g, b);
    }
    // g
    if (abs(r - b) % 3 == 0) {
        p2 = max(r, b);
    }
    // b
    if (abs(r - g) % 3 == 0) {
        p3 = max(r, g);
    }
    int ans = min(p1, min(p2, p3));
    if (ans != mx) {
        return ans;
    }
    return -1;
}

// Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools templates:
// (https://github.com/imishinist/competitive/blob/master/boilerplate/main.cpp)
int main() {
    int T;
    cin >> T;
    for (int i = 0; i < T; i++){
        ll r, g, b;
        cin >> r >> g >> b;
        cout << solve(r, g, b) << endl;
    }
    return 0;
}
