#include <algorithm>
#include <atcoder/all>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iomanip>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>

using namespace std;

using ll = long long;

#define rep(i, n) for (int(i) = 0; (i) < (n); (i)++)
#define reps(i, ini, n) for (int(i) = (ini); (i) < (n); (i)++)
#define rev(i, n) for (int(i) = n; (i) >= 0; (i)--)
#define revs(i, from, to) for (int(i) = from; (i) >= to; (i)--)
#define eps 1e-14

const string YES = "Yes";
const string NO = "No";

bool check(vector<vector<ll>> &s, ll n, ll m) {
    rep(i, n) {
        for (int j = 1; j < m; j++) {
            if (s[i][j-1] % 7 == 0) {
                return false;
            }
            if (s[i][j] - s[i][j-1] != 1) {
                return false;
            }
        }
    }

    rep(j, m) {
        for (int i = 1; i < n; i++) {
            if (s[i][j] - s[i-1][j] != 7) {
                return false;
            }
        }
    }

    return true;
}

// Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools templates:
// (https://github.com/imishinist/competitive/blob/master/boilerplate/main.cpp)
int main() {
    int n, m;
    cin >> n >> m;
    vector<vector<ll>> B = vector<vector<ll>>(n, vector<ll>(m));

    rep(i, n) {
        rep(j, m) {
            ll b;
            cin >> b;
            B[i][j] = b;
        }
    }

    if (check(B, n, m)) {
        cout << YES << endl;
    } else {
        cout << NO << endl;
    }

    return 0;
}
