#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;

typedef long long ll;

#define rep(i,n) for (int (i) = 0; (i) < (n); (i)++)
#define reps(i,ini,n) for (int (i) = (ini); (i) < (n); (i)++)
#define rev(i,n) for (int (i) = n; (i) >= 0; (i)--)
#define revs(i,from,to) for (int (i) = from; (i) >= to; (i)--)
#define eps 1e-14

{% if mod %}
const long long MOD = {{ mod }};
{% endif %}
{% if yes_str %}
const string YES = "{{ yes_str }}";
{% endif %}
{% if no_str %}
const string NO = "{{ no_str }}";
{% endif %}

{% if prediction_success %}
void solve({{ formal_arguments }}){

}
{% endif %}

// Generated by {{ atcodertools.version }} {{ atcodertools.url }} templates: (https://github.com/imishinist/competitive/blob/master/boilerplate/main.cpp)
int main(){
    {% if prediction_success %}
    {{input_part}}
    solve({{ actual_arguments }});
    {% else %}
    // Failed to predict input format
    {% endif %}
    return 0;
}
