#include <algorithm>
#include <atcoder/all>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iomanip>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>

using namespace std;

typedef long long ll;

#define rep(i, n) for (int(i) = 0; (i) < (n); (i)++)
#define reps(i, ini, n) for (int(i) = (ini); (i) < (n); (i)++)
#define rev(i, n) for (int(i) = n; (i) >= 0; (i)--)
#define revs(i, from, to) for (int(i) = from; (i) >= to; (i)--)
#define eps 1e-14

void solve(long long L, long long R, std::vector<long long> A,
           std::vector<long long> B, std::vector<std::vector<long long>> C) {}

// Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools templates:
// (https://github.com/imishinist/competitive/blob/master/boilerplate/main.cpp)
int main() {
    long long L;
    std::scanf("%lld", &L);
    long long R;
    std::scanf("%lld", &R);
    std::vector<long long> A(L);
    for (int i = 0; i < L; i++) {
        std::scanf("%lld", &A[i]);
    }
    std::vector<long long> B(R);
    for (int i = 0; i < R; i++) {
        std::scanf("%lld", &B[i]);
    }
    std::vector<std::vector<long long>> C(L, std::vector<long long>(R));
    for (int i = 0; i < L; i++) {
        for (int j = 0; j < R; j++) {
            std::scanf("%lld", &C[i][j]);
        }
    }
    solve(L, R, std::move(A), std::move(B), std::move(C));
    return 0;
}
