#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

typedef vector<int> vi;
typedef vector<pair<int, int>> vpii;

#define eps 1e-14

const string YES = "Yes";
const string NO = "No";

void solve(std::string S, std::string T) {
    if (S == T) {
        cout << YES << endl;
        return;
    }

    for (int i = 0; i < S.size() - 1; i++) {
        string tmp = S;
        char t = tmp[i];
        tmp[i] = tmp[i+1];
        tmp[i+1] = t;
        if (tmp == T) {
            cout << YES << endl;
            return;
        }
    }
    cout << NO << endl;
    return;
}

// Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools templates:
// (https://github.com/imishinist/competitive/blob/master/boilerplate/main.cpp)
int main() {
    std::string S;
    std::cin >> S;
    std::string T;
    std::cin >> T;
    solve(S, T);
    return 0;
}
